# Generated by Django 4.0.5 on 2022-06-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
