# Generated by Django 4.0.5 on 2022-06-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_image_alter_customer_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_of_purchases',
            field=models.IntegerField(default=0),
        ),
    ]
