# Generated by Django 4.0.5 on 2022-07-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_invoice_delivered_remove_invoice_packed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Initialized', 'Initialized'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Reached Distribution Centre', 'Reached Distribution Centre'), ('Delivered', 'Delivered')], default='Initialized', max_length=30),
        ),
    ]
