# Generated by Django 4.0.5 on 2022-07-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
