# Generated by Django 4.0.5 on 2022-07-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_order_has_paid_order_stripe_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
