# Generated by Django 4.0.5 on 2022-07-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reason',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='want_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Debit Card'), ('UPI', 'UPI')], default='Card', max_length=30),
        ),
    ]
