# Generated by Django 4.0.5 on 2022-07-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_invoice_is_picked_invoice_is_returned_invoice_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/product_images'),
        ),
    ]
