# Generated by Django 4.0.5 on 2022-08-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_searchednotify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchednotify',
            old_name='customer',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='searchednotify',
            old_name='product',
            new_name='product_name',
        ),
    ]
